language: objective-c
osx_image: xcode9.2
xcode_project: iosu.xcworkspace
xcode_scheme: iosu
xcode_sdk: iphonesimulator11.2
script:
- pod install
- pod update
- xcodebuild clean build -sdk iphonesimulator -workspace iosu.xcworkspace -scheme iosu CODE_SIGNING_REQUIRED=NO
