os: osx
osx_image: xcode10.2

install:
  - pod install --repo-update

script:
  - xcodebuild -scheme iosu -workspace iosu.xcworkspace -configuration Release clean archive -archivePath "build/iosu.xcarchive" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty
